services:
  postgres:
    image: postgres:16
    container_name: sahayak-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sahayak-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sahayak-backend
    restart: unless-stopped

    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      FRONTEND_URL: ${FRONTEND_URL}

    ports:
      - "5000:5000"
    
    depends_on:
      - postgres

    networks:
      - sahayak-network 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    container_name: sahayak-frontend
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - postgres
      - backend

    networks:
      - sahayak-network


volumes:
  postgres_data:

networks:
  sahayak-network:
    name: sahayak-network
    driver: bridge